### ISSUE TITLE
Problème java.lang.NoSuchMethodException

### ISSUE THREAD

**Issue by hugohahn** [emlyon/codapps#29]
Bonjour,

lorsque je lance mon app, plusieurs lignes en rouge s'affichent ainsi que la dernière "build successful " en vert.
Quelle est la source du problème ? Merci d'avance

java.lang.NoSuchMethodException: com.hugohahn.Form1.init(java.lang.Object)
	at java.lang.Class.getDeclaredMethod(Class.java:2130)
	at com.codename1.impl.javase.Executor$1.run(Executor.java:100)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Java Result: 1
BUILD SUCCESSFUL (total time: 1 second) ( cette dernière est en vert)

**Comment by seinecle** [comment]
Bonsoir,
C'est assez mystérieux, il faudrait que je voie le code de votre fichier Form1.java

**Comment by seinecle** [comment]
Bonjour, une réponse a été apportée à cette issue il y a plusieurs jours. Je la clos en la considérant résolue. Si ce n'est pas le cas, vous pouvez la réouvrir. Si vous avez une nouvelle question, merci de ne pas réouvrir cette issue, mais créez-en plutôt une autre.
